// <auto-generated />
namespace StudentSmartCard.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class student_card_update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(student_card_update));
        
        string IMigrationMetadata.Id
        {
            get { return "202005032005255_student_card_update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
