// <auto-generated />
namespace StudentSmartCard.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class scancardinformation_update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(scancardinformation_update));
        
        string IMigrationMetadata.Id
        {
            get { return "202005032155422_scancardinformation_update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
